baseURL = "https://www.adventuremeng.com"
title = "Adventure Meng"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = "© Meng Gao, 2019 · Made with blogdown and the Minimo theme for Hugo"

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "Urban Planning, GIS, R"
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )


######Try adding a link on Aug 26:
[[menu.main]]
#Delete bilibili button on Sep 20 2019:
#name = "哔哩哔哩"
#weight = -10
#identifier = "bilibili"
#url = "https://space.bilibili.com/12234819"



#####Try adding another link on Aug 27:
[[menu.main]]
name = "POSTS"
weight = -210
identifier = "post"
url = "/post"

[[menu.main]]
name = "中文"
weight = -210
identifier = "cn_post"
url = "/cn_post"
#####
[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideEntryMeta = ["page"] # boolean / array of sections
showReadingTime = true
showLastmod = true
taxonomyCloudShuffle = true
accentColor = "#00ccff"  #0, 204, 255 color RGB
hideMainMenu = false
rtl = false

[params.sidebar]
enable = true

[params.widgets]
header = ["breadcrumbs"]
homepage = ["recent_posts"]
sidebar = ["about","search","taxonomy_cloud"] #"sidebar_menu"  That I take out
footer = ["social_menu"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]

email = "menggao114[at]gmail.com"
instagram = "meng_gao233"

[params.comments]
enable = true

# Isso: https://posativ.org/isso/
[params.comments.isso]
enable = false
scriptSrc = "" # "https://isso.example.com/js/embed.min.js"
dataAttrs = "" # "data-isso='https://isso.example.com' data-isso-require-author='true'"

[params.comments.staticman]
enable = false
apiEndpoint = "https://dev.staticman.net/v3/entry/github/adventuremeng/adventuremeng/master"
maxDepth = 2
username = "adventuremeng"
repository = "adventuremeng"

# Utterances: https://utteranc.es
[params.comments.utterances]
enable = true
issueTerm = "pathname" # pathname / url / title

[params.comments.utterances.github]
username = "adventuremeng"
repository = "adventuremeng"

[params.search]
client = "fuse" # algolia / fuse / lunr

[params.search.algolia]
appId = ""
indexName = ""
searchApiKey = ""

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"



[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1
